const fs = require("fs");
const path = require("path");

function wp(f, c) {
  const d = path.dirname(f);
  if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true });
  fs.writeFileSync(f, c, "utf8");
  console.log("OK:", f);
}

// Mock Data
wp("mock/users.json", JSON.stringify([
  { id: 1, username: "admin", password: "123456", realName: "管理员", role: "admin", roleName: "超级管理员", department: "技术部", email: "admin@example.com", phone: "13800138000", avatar: "", status: 1, permissions: ["*"] },
  { id: 2, username: "manager", password: "123456", realName: "张经理", role: "manager", roleName: "运营经理", department: "运营部", email: "manager@example.com", phone: "13800138001", avatar: "", status: 1, permissions: ["user:view", "user:create", "user:update", "order:view", "order:create", "order:update", "ticket:view", "ticket:create", "ticket:update", "message:view", "message:send", "log:view", "log:export", "dashboard:view"] },
  { id: 3, username: "operator", password: "123456", realName: "李专员", role: "operator", roleName: "运营专员", department: "运营部", email: "operator@example.com", phone: "13800138002", avatar: "", status: 1, permissions: ["user:view", "order:view", "order:create", "ticket:view", "ticket:create", "message:view", "log:view", "dashboard:view"] },
  { id: 4, username: "viewer", password: "123456", realName: "王访客", role: "viewer", roleName: "访客", department: "访客", email: "viewer@example.com", phone: "13800138003", avatar: "", status: 1, permissions: ["user:view", "order:view", "ticket:view", "message:view", "dashboard:view"] }
], null, 2));

// API Documentation
wp("docs/api.md", "# API 接口文档\n\n## 接口列表\n\n### 认证接口\n\n- POST /api/auth/login - 用户登录\n- POST /api/auth/refresh - 刷新 Token\n- GET /api/auth/userinfo - 获取用户信息\n- GET /api/auth/menus - 获取用户菜单\n- GET /api/auth/permissions - 获取用户权限\n- POST /api/auth/logout - 退出登录\n\n### 用户接口\n\n- GET /api/users - 获取用户列表\n- GET /api/users/:id - 获取用户详情\n- POST /api/users - 创建用户\n- PUT /api/users/:id - 更新用户\n- DELETE /api/users/:id - 删除用户\n\n### 订单接口\n\n- GET /api/orders - 获取订单列表\n- GET /api/orders/:id - 获取订单详情\n- POST /api/orders - 创建订单\n- PUT /api/orders/:id - 更新订单\n- DELETE /api/orders/:id - 删除订单\n\n### 工单接口\n\n- GET /api/tickets - 获取工单列表\n- GET /api/tickets/:id - 获取工单详情\n- POST /api/tickets - 创建工单\n- PUT /api/tickets/:id - 更新工单\n- DELETE /api/tickets/:id - 删除工单\n\n### 消息接口\n\n- GET /api/messages - 获取消息列表\n- GET /api/messages/unread-count - 获取未读消息数\n- GET /api/messages/:id - 获取消息详情\n- POST /api/messages - 发送消息\n- PUT /api/messages/:id/read - 标记已读\n- PUT /api/messages/read-all - 全部已读\n- DELETE /api/messages/:id - 删除消息\n\n### 日志接口\n\n- GET /api/logs - 获取操作日志\n- POST /api/logs/export - 导出日志\n\n### 看板接口\n\n- GET /api/dashboard/stats - 获取统计数据\n- GET /api/dashboard/chart/trend - 获取趋势图数据\n- GET /api/dashboard/chart/pie - 获取饼图数据\n- GET /api/dashboard/chart/bar - 获取柱状图数据\n- GET /api/dashboard/activities - 获取最近活动\n\n### 聚合接口\n\n- GET /api/aggregate/home - 首页聚合数据\n- GET /api/aggregate/user-detail - 用户详情聚合\n- GET /api/aggregate/order-detail - 订单详情聚合\n\n## 统一响应格式\n\n`json\n{\n  \"code\": 200,\n  \"message\": \"success\",\n  \"data\": {}\n}\n`\n\n## 错误码说明\n\n- 200: 成功\n- 401: 未授权\n- 403: 无权限\n- 404: 资源不存在\n- 500: 服务器错误\n- 503: 服务不可用\n- 504: 服务超时\n"
);

// Test Guide
wp("docs/test-guide.md", "# 测试说明\n\n## 测试账号\n\n| 用户名 | 密码 | 角色 | 权限说明 |\n|--------|------|------|----------|\n| admin | 123456 | 超级管理员 | 所有权限 |\n| manager | 123456 | 运营经理 | 用户/订单/工单管理、消息发送、日志导出 |\n| operator | 123456 | 运营专员 | 用户查看、订单/工单创建、消息查看 |\n| viewer | 123456 | 访客 | 只读权限 |\n\n## 功能测试\n\n### 1. 登录功能\n\n`ash\ncurl -X POST http://localhost:3000/api/auth/login \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\"username\":\"admin\",\"password\":\"123456\"}'\n`\n\n预期返回：\n`json\n{\n  \"code\": 200,\n  \"message\": \"success\",\n  \"data\": {\n    \"token\": \"eyJhbGciOiJIUzI1NiIs...\",\n    \"refreshToken\": \"eyJhbGciOiJIUzI1NiIs...\",\n    \"userInfo\": {\n      \"id\": 1,\n      \"username\": \"admin\",\n      \"realName\": \"管理员\",\n      \"role\": \"admin\",\n      \"roleName\": \"超级管理员\"\n    }\n  }\n}\n`\n\n### 2. 获取用户信息\n\n`ash\ncurl http://localhost:3000/api/auth/userinfo \\\n  -H \"Authorization: Bearer <token>\"\n`\n\n### 3. 获取用户列表\n\n`ash\ncurl \"http://localhost:3000/api/users?page=1&pageSize=10\" \\\n  -H \"Authorization: Bearer <token>\"\n`\n\n### 4. 获取订单列表\n\n`ash\ncurl \"http://localhost:3000/api/orders?page=1&pageSize=10\" \\\n  -H \"Authorization: Bearer <token>\"\n`\n\n### 5. 获取工单列表\n\n`ash\ncurl \"http://localhost:3000/api/tickets?page=1&pageSize=10\" \\\n  -H \"Authorization: Bearer <token>\"\n`\n\n### 6. 获取消息列表\n\n`ash\ncurl \"http://localhost:3000/api/messages?page=1&pageSize=20\" \\\n  -H \"Authorization: Bearer <token>\"\n`\n\n### 7. 获取操作日志\n\n`ash\ncurl \"http://localhost:3000/api/logs?page=1&pageSize=10\" \\\n  -H \"Authorization: Bearer <token>\"\n`\n\n### 8. 获取看板数据\n\n`ash\ncurl http://localhost:3000/api/dashboard/stats \\\n  -H \"Authorization: Bearer <token>\"\n`\n\n## 权限测试\n\n### 测试按钮权限\n\n1. 使用 dmin 登录，应该可以看到所有按钮（新增、编辑、删除、导出）\n2. 使用 iewer 登录，应该只能看到查看按钮，新增/编辑/删除按钮隐藏\n\n### 测试菜单权限\n\n1. 使用 dmin 登录，应该可以看到所有菜单（看板、用户、订单、工单、消息、日志）\n2. 使用 iewer 登录，应该看不到操作日志菜单\n\n## BFF 层特性测试\n\n### 测试超时处理\n\n`ash\n# 模拟超时请求，应该在 5 秒内返回 504 错误\ncurl -m 6 http://localhost:3000/api/timeout-test\n`\n\n### 测试降级处理\n\n当下游服务不可用时，应该返回降级数据而不是 500 错误\n\n### 测试缓存\n\n相同的 GET 请求在缓存有效期内（默认 5 分钟）应该从缓存返回\n\n### 测试统一错误处理\n\n所有错误响应都应该包含统一的格式：\n`json\n{\n  \"code\": 500,\n  \"message\": \"错误信息\",\n  \"data\": null,\n  \"timestamp\": \"2024-01-01T00:00:00.000Z\",\n  \"path\": \"/api/users\"\n}\n`\n\n## 前端测试\n\n1. 访问 http://localhost:5173 打开前端应用\n2. 使用不同账号登录，验证功能权限\n3. 测试页面间切换，验证全局筛选条件共享\n4. 测试全局消息中心，验证消息通知功能\n5. 测试个人中心，验证修改密码功能\n6. 测试错误页面，访问 /404、/403、/500\n\n## 性能测试\n\n使用 Apache Bench 进行并发测试：\n\n`ash\n# 测试登录接口\nab -n 1000 -c 100 -p login.json -T application/json \\\n  http://localhost:3000/api/auth/login\n\n# 测试用户列表接口\nab -n 1000 -c 100 -H \"Authorization: Bearer <token>\" \\\n  \"http://localhost:3000/api/users?page=1&pageSize=10\"\n`\n"
);

// Root package.json with all scripts
wp("scripts/init-mock.js", "const fs = require('fs');\nconst path = require('path');\n\nconsole.log('=== 初始化演示数据 ===');\nconsole.log('');\nconsole.log('测试账号：');\nconsole.log('  admin / 123456 - 超级管理员');\nconsole.log('  manager / 123456 - 运营经理');\nconsole.log('  operator / 123456 - 运营专员');\nconsole.log('  viewer / 123456 - 访客');\nconsole.log('');\nconsole.log('端口说明：');\nconsole.log('  Web: 5173');\nconsole.log('  BFF: 3000');\nconsole.log('  User Service: 3001');\nconsole.log('  Order Service: 3002');\nconsole.log('  Ticket Service: 3003');\nconsole.log('  Notification Service: 3004');\nconsole.log('');\nconsole.log('演示数据已就绪！');\n"
);

console.log('=== Mock data, docs and test guide generated! ===');